name: 'Push CED source files'
description: 'Github Action to push source files to CloudEdgeDistribution'
inputs:
  cli-token:
    description: "CloudEdgeDistribution CLI token. If not specified it'll try to resolve the CLI token from environment variable CED_CLI_TOKEN."
    required: false
  environment:
    description: "Environment to use in CloudEdgeDistribution. If not specified it'll try to resolve it from environment variable CED_ENVIRONMENT, it'll use the default environment in ced.json otherwise."
    required: false
  path:
    description: "Path to the CloudEdgeDistribution project. If not specified it'll try to resolve it from environment variable CED_PROJECT_PATH, it'll use current folder otherwise."
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
